[tools]
"cargo:trunk" = "latest"
rust = { version = "stable", targets = "wasm32-unknown-unknown" }

[tasks."dev:app"]
run = "trunk serve"
dir = "{{ cwd }}/crates/app"

[tasks."dev:daemon"]
run = "cargo run"
dir = "{{ cwd }}/crates/daemon"
