[tools]
"cargo:leptosfmt" = "latest"
"cargo:trunk" = "latest"
rust = { version = "stable", targets = "wasm32-unknown-unknown" }

[tasks."dev:app"]
run = "trunk serve --open"
dir = "{{ cwd }}/crates/app"

[tasks."dev:daemon"]
run = "cargo run"
dir = "{{ cwd }}/crates/daemon"

[tasks."fmt:leptos"]
run = "leptosfmt ."
dir = "{{ cwd }}/crates/app"

[tasks.fmt]
depends = ["fmt:leptos"]
run = "cargo fmt"
