[build]
publish = "public"
command = "git submodule update --init && zola build"

[build.environment]
ZOLA_VERSION = "0.19.2"

[context.deploy-preview]
command = "git submodule update --init && zola build --base-url $DEPLOY_PRIME_URL"
