name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-rust:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "27"
          gleam-version: "1.10"
          rebar3-version: "3"
      - name: Install dependencies
        run: gleam deps download
      - name: Check formatting
        run: gleam format --check src test
      - name: Run tests
        run: gleam test
